# numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.
File automatically generated. See the documentation to update questions/answers/hints programmatically.


#### 1. Import the numpy package under the name `np` (★☆☆)
`hint: import … as`

In [3]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆)
`hint: np.zeros`

In [4]:
v = np.array([1,2,3,4,5,6,7,8,9,10])

In [5]:
v.size

10

In [6]:
v.shape

(10,)

#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
`hint: array[4]`

In [7]:
n = np.array([5,2,3,4,1,6,7,8,9,10])

In [8]:
n[4]

1

#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
`hint: arange`

In [9]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
`hint: reshape`

In [10]:
matrix = np.arange(0, 9).reshape((3, 3))
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
`hint: np.nonzero`

In [11]:
nonzero_list = [1,2,0,0,4,0]

In [12]:
np.nonzero(nonzero_list)

(array([0, 1, 4]),)

#### 7. Create a 3x3 identity matrix (★☆☆)
`hint: np.eye`

In [13]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 8. Create a 3x3x3 array with random values (★☆☆)
`hint: np.random.random`

In [14]:
np.random.random((3, 3, 3))

array([[[0.92617906, 0.83190229, 0.06099687],
        [0.81248956, 0.93281051, 0.5909247 ],
        [0.24737969, 0.41363182, 0.35095441]],

       [[0.60556042, 0.92533847, 0.78709705],
        [0.65638118, 0.88049408, 0.51677094],
        [0.40410037, 0.29498082, 0.61753416]],

       [[0.48033008, 0.96791346, 0.2415373 ],
        [0.84693601, 0.88093968, 0.12351219],
        [0.32940991, 0.1583394 , 0.50730878]]])

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
`hint: min, max`

In [15]:
array = np.random.random((10, 10)).reshape((10, 10))
print(array)

[[0.25046002 0.66403863 0.22080886 0.35785121 0.918353   0.12084824
  0.74750643 0.81245992 0.2150498  0.44109435]
 [0.86755711 0.67876041 0.8948609  0.81882653 0.08812471 0.17697179
  0.48409905 0.99606333 0.16782982 0.87156206]
 [0.67210946 0.8711753  0.38773079 0.43518971 0.63876229 0.02566377
  0.25942805 0.46626504 0.98441858 0.89939178]
 [0.13172396 0.68033105 0.92913044 0.11988846 0.05332223 0.98644727
  0.69528771 0.33441042 0.78830968 0.93137676]
 [0.60554005 0.70195827 0.46860473 0.60921011 0.51812479 0.52870227
  0.62620225 0.61944567 0.54575156 0.23947315]
 [0.5499175  0.02916237 0.3845172  0.55163615 0.83682798 0.59992578
  0.06833822 0.48350378 0.36394686 0.89948768]
 [0.67178828 0.89992666 0.26923236 0.53410884 0.27515289 0.34530518
  0.69809142 0.67309643 0.32058232 0.04780022]
 [0.79458855 0.40144866 0.26475244 0.34264988 0.38275416 0.70562291
  0.71830725 0.86197202 0.3339789  0.88929201]
 [0.31230547 0.12451304 0.16811181 0.06011915 0.30252798 0.52969014
  0.3534574 

#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
`hint: mean`

In [16]:
rv = np.random.random((30))

In [17]:
np.mean(rv)

0.5922309655687052

#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`hint: np.diag`

In [18]:
diagonal = np.zeros((5,5))

In [19]:
diagonal

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
diagonal += np.arange(5)

In [21]:
diagonal

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [22]:
np.diag(diagonal, k = -1)

array([0., 1., 2., 3.])

In [23]:
#array needs to start with "1" instead of "0"

#### 12. Normalize a 5x5 random matrix (★☆☆)
`hint: (x -mean)/std`

In [24]:
rand = np.random.random((5,5))

In [25]:
(rand - np.mean(rand))/np.std(rand)

array([[-1.12936888, -0.89179129,  1.21364343,  1.33459514,  1.06201032],
       [ 1.482935  ,  1.43643618,  0.63095285,  1.35017544,  0.67966631],
       [-0.54348815, -0.2555634 , -0.81364456,  0.08138677, -1.29796656],
       [-0.78524359, -0.71202377, -1.41154045,  0.79386107, -0.33664857],
       [-0.66278667, -1.14274149, -0.40705645,  1.40000305, -1.07580174]])

#### 13. How to find common values between two arrays? (★☆☆)
`hint: np.intersect1d`

In [26]:
np.intersect1d([1, 2, 3, 4], [0, 1, 2, 3])

array([1, 2, 3])

#### 14. Create a random vector of size 10 and sort it (★★☆)
`hint: sort`

In [27]:
rv_s = np.sort(np.random.random((10)))

In [28]:
rv_s

array([0.1261708 , 0.19926144, 0.32160049, 0.37652758, 0.46976874,
       0.46994638, 0.60065585, 0.63633262, 0.64307449, 0.90511748])

#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
`hint: argmax`

In [29]:
rv_max = np.random.random((10))

In [39]:
rv_max

array([0.21079518, 0.59086436, 0.43254626, 0.47146309, 0.        ,
       0.08660176, 0.1501903 , 0.06439737, 0.02568697, 0.10689971])

In [40]:
# argmax returns index of biggest number 

rv_max[np.argmax(rv_max)]

0.5908643641076861

In [41]:
rv_max[np.argmax(rv_max)] = 0

#### 16. Subtract the mean of each row of a matrix (★★☆)
`hint: mean(axis=,keepdims=)`

In [ ]:
matrix = np.arange(0, 9).reshape((3, 3))

matrix - np.mean(matrix, axis=1)

#### 17. How to get the n largest values of an array (★★★)
`Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
hint: np.argsort | np.argpartition`

In [ ]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

In [ ]:
np.argsort(Z)

In [ ]:
np.argpartition(Z, 5)

#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
`hint: np.where

In [ ]:
matrix = np.arange(15).reshape((5, 3))

In [ ]:
matrix

In [ ]:
np.where(matrix > 4, matrix, matrix**2)