# numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.
File automatically generated. See the documentation to update questions/answers/hints programmatically.


#### 1. Import the numpy package under the name `np` (★☆☆)
`hint: import … as`

In [1]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆)
`hint: np.zeros`

In [5]:
v = np.array([1,2,3,4,5,6,7,8,9,10])

In [6]:
v.size

10

In [7]:
v.shape

(10,)

#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
`hint: array[4]`

In [8]:
n = np.array([5,2,3,4,1,6,7,8,9,10])

In [9]:
n[4]

1

#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
`hint: arange`

In [11]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
`hint: reshape`

In [12]:
matrix = np.arange(0, 9).reshape((3, 3))
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
`hint: np.nonzero`

In [14]:
nonzero_list = [1,2,0,0,4,0]

In [15]:
np.nonzero(nonzero_list)

(array([0, 1, 4]),)

#### 7. Create a 3x3 identity matrix (★☆☆)
`hint: np.eye`

In [18]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 8. Create a 3x3x3 array with random values (★☆☆)
`hint: np.random.random`

In [20]:
np.random.random((3, 3, 3))

array([[[0.35577181, 0.46298335, 0.17832875],
        [0.36501087, 0.81312433, 0.66583356],
        [0.13372639, 0.35137434, 0.38752689]],

       [[0.83067119, 0.69021684, 0.44613838],
        [0.22572101, 0.46918091, 0.58355409],
        [0.75294247, 0.55401602, 0.55876967]],

       [[0.08248484, 0.77510445, 0.41076417],
        [0.33655333, 0.19033061, 0.95966343],
        [0.09805218, 0.26171152, 0.87184274]]])

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
`hint: min, max`

In [25]:
array = np.random.random((10, 10)).reshape((10, 10))
print(array)

[[0.16966629 0.9325377  0.50540955 0.85500486 0.55143878 0.8747343
  0.09046383 0.93755787 0.43238846 0.93984926]
 [0.0538998  0.71838799 0.4564939  0.97370501 0.45149685 0.06076588
  0.65435743 0.282644   0.6614273  0.99343755]
 [0.55804733 0.82222225 0.0694091  0.26832777 0.17344743 0.72051641
  0.47970673 0.75602566 0.88031613 0.20844699]
 [0.3829432  0.84438419 0.90744512 0.68237697 0.23358727 0.4646651
  0.41287246 0.70189589 0.37368939 0.08014176]
 [0.5441341  0.54915246 0.82504399 0.2874267  0.24591557 0.66029958
  0.72918588 0.75024709 0.59453785 0.91538555]
 [0.93962643 0.85416687 0.28480458 0.27439002 0.40927065 0.8917166
  0.08732323 0.72625066 0.3950441  0.62260603]
 [0.10974007 0.55084902 0.52154578 0.51830841 0.38338271 0.57693084
  0.34477443 0.54067996 0.92998356 0.25740313]
 [0.53646719 0.34447533 0.09791409 0.96986025 0.01323398 0.55285508
  0.47122179 0.65633142 0.20439413 0.44259502]
 [0.20697688 0.32964923 0.43440747 0.05241075 0.67773078 0.22902603
  0.99626715 0.

#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
`hint: mean`

In [26]:
rv = np.random.random((30))

In [30]:
np.mean(rv)

0.4186120290896647

#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`hint: np.diag`

In [95]:
diagonal = np.zeros((5,5))

In [96]:
diagonal

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [97]:
diagonal += np.arange(5)

In [98]:
diagonal

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [99]:
np.diag(diagonal, k = -1)

array([0., 1., 2., 3.])

In [ ]:
#array needs to start with "1" instead of "0"

#### 12. Normalize a 5x5 random matrix (★☆☆)
`hint: (x -mean)/std`

In [107]:
rand = np.random.random((5,5))

In [108]:
(rand - np.mean(rand))/np.std(rand)

array([[ 1.14731143, -1.55403321, -1.14120851,  0.31492517,  1.72963393],
       [ 0.64073923, -0.36751132, -1.15578795, -0.27322325, -1.84188302],
       [ 0.28522449,  0.89456783, -1.53861239,  1.23688996,  0.66927799],
       [ 0.27382345,  0.89174555,  0.74430517, -0.39931871, -0.09400646],
       [ 1.3306771 , -0.77193268, -1.44239272,  0.50365465, -0.08286572]])

#### 13. How to find common values between two arrays? (★☆☆)
`hint: np.intersect1d`

In [109]:
np.intersect1d([1, 2, 3, 4], [0, 1, 2, 3])

array([1, 2, 3])

#### 14. Create a random vector of size 10 and sort it (★★☆)
`hint: sort`

In [115]:
rv_s = np.sort(np.random.random((10)))

In [116]:
rv_s

array([0.1678036 , 0.23735605, 0.43917179, 0.50093723, 0.62134709,
       0.6806946 , 0.74339992, 0.80010388, 0.86545978, 0.99072524])

#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
`hint: argmax`

In [124]:
rv_max = np.random.random((10))

In [125]:
rv_max

array([0.85662237, 0.0013305 , 0.56691817, 0.59847265, 0.59838819,
       0.26551611, 0.63948416, 0.85137226, 0.50011829, 0.20684158])

In [127]:
np.argmax(rv_max)

0

#### 16. Subtract the mean of each row of a matrix (★★☆)
`hint: mean(axis=,keepdims=)`

In [129]:
matrix = np.arange(0, 9).reshape((3, 3))

matrix - np.mean(matrix, axis=1)

array([[-1., -3., -5.],
       [ 2.,  0., -2.],
       [ 5.,  3.,  1.]])

#### 17. How to get the n largest values of an array (★★★)
`Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
hint: np.argsort | np.argpartition`

In [130]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

In [131]:
np.argsort(Z)

array([3687, 7065, 8327, ..., 9904, 4508, 3250])

In [133]:
np.argpartition(Z, 5)

array([3687, 7065,  946, ..., 9997, 9998, 4999])

#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
`hint: np.where

In [138]:
matrix = np.arange(15).reshape((5, 3))

In [136]:
matrix

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [142]:
np.where(matrix > 4, matrix, matrix**2)

array([[ 0,  1,  4],
       [ 9, 16,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])